### ISSUE TITLE
如果能支持代码高亮就完美了

### ISSUE THREAD

**Issue by jeanboydev** [lyricat/wechat-format#10]

**Comment by lyricat** [comment]
支持。请看示例 markdown 里面的说明。

**Comment by jeanboydev** [comment]
又仔细看了下 markdown 说明，但是输出效果是代码都是黑色的呀，没有看到关键字高亮显示。

**Comment by lyricat** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/67439/54688465-99bcc000-4b58-11e9-9806-7fcbfda64819.png">

**Comment by jeanboydev** [comment]
原来是这样，多谢多谢
