### ISSUE TITLE
关于列表的小圆点

### ISSUE THREAD

**Issue by wanghusw** [lyricat/wechat-format#12]
将输出复制到微信后，在调整字体大小、缩进、对齐时好像要按照一定的顺序，列表的小圆点才能不发生位移（一般是向左移动）并且造成格式丢失，具体顺序我要再试一下，不知道为什么会这样。

**Comment by lyricat** [comment]
@wanghusw 试好了没？

**Comment by wanghusw** [comment]
@lyricat 这些天日更里面没用到列表，我会找个时间测试一下，然后在这里反馈。2019-03-25 23:31:49

**Comment by wanghusw** [comment]
在调整列表的「两端缩进」以及「字号」的时候都会发生位移（错位），调整「对齐」并不会发生（位移）

**Comment by lyricat** [comment]
@wanghusw 我没法保证列表项在微信编辑器里调整样式没有问题。

**Comment by wanghusw** [comment]
@lyricat 嗯，我想也是这样，这正是这个工具的初衷，对吧，昨天我在想也许该直接用您的模板，把排版的时间节省下来。感谢回复。我把 Issues 关闭。

**Comment by lyricat** [comment]
@wanghusw 主要是微信编辑器对 list 的行为很奇怪。所以没办法
