### ISSUE TITLE
fork过去修改完自己的css，然后怎么用？

### ISSUE THREAD

**Issue by rouor** [lyricat/wechat-format#13]
您好，我是小白，fork你的项目，把其中涉及css的部分换成我自己的code，然后呢？
你有下面这个网页的平台，但是我修改完以后，怎么把我的markdown生成最后的微信公众号格式呢？

https://lab.lyric.im/wxformat

**Comment by maoruibin** [comment]
你直接在电脑上点击 src 中的 index.html ，选择用浏览器打开就可以。

**Comment by lyricat** [comment]
@rouor 如果你的 theme 够好看，可以发个 pull request 给我。

**Comment by rouor** [comment]
> 你直接在电脑上点击 src 中的 index.html ，选择用浏览器打开就可以。

thanks, 懂了

**Comment by rouor** [comment]
> @rouor 如果你的 theme 够好看，可以发个 pull request 给我。

哈，的确觉得还不错，我这两天有点忙，忙过去，我给你pull request 你先看下吧。

**Comment by lyricat** [comment]
新的 code 里 @pengloo53 做了主题支持，你可以看看。
