### ISSUE TITLE
Bug report li ol hierarchy missing

### ISSUE THREAD

**Issue by alswl** [lyricat/wechat-format#15]
Original markdown:

```
*   个人好物
    *   Nitendo Switch + 塞尔达传说
    *   天猫精灵：前后购入 4 个，小朋友最爱
    *   小米之家运动鞋：物美价廉

```

Rendered in self hosted web site:

![image](https://user-images.githubusercontent.com/227562/55476937-727eec00-564a-11e9-8c9d-0521eb69109a.png)

Rendered in wechat:

![image](https://user-images.githubusercontent.com/227562/55476738-f389b380-5649-11e9-83ff-b5768ecc3a14.png)

**Comment by lyricat** [comment]
你发个 PR 嘛

**Comment by lyricat** [comment]
你发个 PR 嘛
