### ISSUE TITLE
在线服务组件加载失败

### ISSUE THREAD

**Issue by pengloo53** [lyricat/wechat-format#19]
发现在线服务前台 Vue 报错，我在服务端测试了一下，显示正常：wechat.90byte.com ，所以猜测你的线上服务有问题，可能需要重启一下。

**Comment by lyricat** [comment]
虽然你没有写是什么错误，但是你的猜测是错误的。因为它没有服务端。

**Comment by pengloo53** [comment]
@lyricat 猜测确实错的，换个浏览器就可以了，用 chrome 就总是报错。

![image](https://user-images.githubusercontent.com/5508125/56459123-d848d300-63c1-11e9-88eb-f78234e5cfa4.png)
