### ISSUE TITLE
关于标题居中问题

### ISSUE THREAD

**Issue by mowangjuanzi** [lyricat/wechat-format#21]
在预览时，标题居中。
复制到微信中时，标题居中。
但是当保存的时候，结果挺好的标题居中效果就没了。

请问这个有办法解决吗？

**Comment by lyricat** [comment]
h2 一直居中的吧。

**Comment by mowangjuanzi** [comment]
可以看看我的微信文章, 标题什么都没了。放进去的时候还好，只要点击保存啊，预览啊，群发之类的，然后标题就没了。

微信文章：https://mp.weixin.qq.com/s/g10CsskcM0p7PXg4yzdIAg 
原文参考：https://www.baoguoxiao.com/2019/02/17/nginx-statistics-request-time/

**Comment by lyricat** [comment]
无法重现。你可以去看看 #22 的文章，是正常居中的

**Comment by mowangjuanzi** [comment]
我把这个给录制成视频了。你瞧瞧

视频地址：链接: https://pan.baidu.com/s/1EE5CIwDF3HJfOUOKjaB9BQ 提取码: qsc7 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by lyricat** [comment]
你用的 Windows 和什么浏览器？要不换个浏览器。
我没有 Windows，所以我没法重现。

**Comment by mowangjuanzi** [comment]
我是用的 windows 10 自带的 edge 浏览器。

明天我到了公司用mac 尝试看看吧

**Comment by lyricat** [comment]
Edge 不支持的话可以理解，不建议使用 Edge。
具体原因要去问微信怎么做的样式清理。
