### ISSUE TITLE
关于代码块的大小和样式问题

### ISSUE THREAD

**Issue by objcoding** [lyricat/wechat-format#25]
现在的代码块字体太大了，是否可以设置一个可动态调整代码块的功能，现在只有格式，没有颜色样式，感觉很简陋，期待加入代码样式选择功能。

**Comment by objcoding** [comment]
![image](https://user-images.githubusercontent.com/24354760/56739823-38fd5480-67a2-11e9-91b5-82687b9f93e4.png)

**Comment by objcoding** [comment]
在现有的格式下，手机屏幕只能代码块左边一半的效果，以及没有颜色，这点对于程序员写作很不友好，况且你这个编排工具，程序员用的最多吧，一般程序员写作只用md，期待大佬把代码块这点优化好。

**Comment by objcoding** [comment]
除了代码块这点，其它都很赞。

**Comment by lyricat** [comment]
代码块用的微信原生组件。复制到微信编辑后点一下代码块就可以着色。

**Comment by lyricat** [comment]
另外代码块可以横线滚动。

**Comment by objcoding** [comment]
横向滚动这个我知道，只是代码块字体太大了，太影响阅读体验了。

**Comment by objcoding** [comment]
12px是最佳的

**Comment by objcoding** [comment]
而且微信原生的，代码行数的显示已经占据很大的位置了，太影响阅读源码了

**Comment by objcoding** [comment]
![image](https://user-images.githubusercontent.com/24354760/56742257-f4c08300-67a6-11e9-9b92-481ae0b8c604.png)

**Comment by lyricat** [comment]
你可以加一个 options，控制使用哪一种代码渲染器。
我个人喜欢微信原生的版本。
