### ISSUE TITLE
链接过滤，自定义颜色，二级列表

### ISSUE THREAD

**Issue by daixiongsheng** [lyricat/wechat-format#28]
可不可以在引用链接的时候对链接进行过滤，比如在本页面跳转的话就不加引用，跳转外部连接再加。

`[图片类](#图片类)    <a href="#图片类">图片类</a>  //  这类就可以不加`

`[Pinterest ](https://www.pinterest.com/) <a href="https://www.pinterest.com/">Pinterest</a>`

如果链接颜色能自定义就理好了。
二级列表似乎识别不了。
![image](https://user-images.githubusercontent.com/28498805/57206060-90e35900-6ff5-11e9-8f93-62a87bda8654.png)

**Comment by lyricat** [comment]
链接过滤倒是容易做，自定义颜色是不可能做的。二级列表由于实现问题，目前依然没支持。
