### ISSUE TITLE
为什么有序列表的输出格式仍然是圆点？

### ISSUE THREAD

**Issue by jwhung** [lyricat/wechat-format#3]
为什么有序列表的输出格式仍然是圆点？
![图片](https://user-images.githubusercontent.com/6926833/54182724-3f2ebe80-44dd-11e9-9914-4b02991db256.png)
![图片](https://user-images.githubusercontent.com/6926833/54182744-4ce44400-44dd-11e9-884b-e6b3a211bc4a.png)

浏览器：Firefox

**Comment by lyricat** [comment]
haha 我把有序列表忘记了

**Comment by cmmei** [comment]
```
- 苹果
- 桃子
- 香蕉
```
设置无序列表的字号为15px, 把输出的复制到微信编辑后台，它并不显示15px，而是 17px ，其它段落文字和设置的一致。是因为 无序列表之间没有空行吗？

**Comment by lyricat** [comment]
@cmmei 当前 master 的版本吗？

**Comment by cmmei** [comment]
是，我昨晚试的时候是这样。之前用 Markdownpad 编辑，复制过去也会这样。

在 2019年3月14日週四 11:20，Lyric Wai <notifications@github.com> 寫道：

**Comment by lyricat** [comment]
微信编辑器会特别处理 ul > li 和 ol > li，把他们的样式剥离掉。所以在 wechat-format 的实现是把列表换成了 section > p，在 macOS Firefox 和 Chrome 下可以修复这个问题。
请问你的操作系统和浏览器是？

**Comment by cmmei** [comment]
WIndows 10 系统的 Chrome ，Ubuntu-Chrome

**Comment by cmmei** [comment]
我那个问题解决了，现在正常了。我用的原来版本，无序列的实心圆点显示有点小。请问这个怎么改？

**Comment by lyricat** [comment]
好的。你可以在 `renderer.listitem = ...` 这个渲染函数里面修改。把默认圆点换成你喜欢的。

**Comment by lyricat** [comment]
可能搞不定了。如果你知道如何搞定，欢迎 PR

**Comment by cmmei** [comment]
```
renderer.listitem = function (text) {
      return '<span ' + S('listitem') + '><span style="margin-right: 10px; font-size: 20px">•</span>' + text + '</span>'
```
试了一下，在 `renderer.listitem` 对 `span` 增加了样式描述 `font-size: 20px` ，不改变后面的文字大小，圆点也变大了。
