### ISSUE TITLE
Bug report, convert failed with unexisted resource

### ISSUE THREAD

**Issue by alswl** [lyricat/wechat-format#40]
## Reproduced steps:

1. use Markdown below:

```
送给亲亲的第一条vlog#和平公园撒欢#也送给大家

<video src="/Users/sunzhen/Downloads/vue_video_cache_filtered_spliced.MOV"></video>
```

2. Copy
3. Paste in wx editor.

## Behavior:

Paste failed.

## Excepted:

Paste successful.

## Others

Browser error message:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/227562/76159881-ca2dad80-615f-11ea-9736-ae51ae9bce73.png">

Browser: Version 81.0.4044.43 (Official Build) beta (64-bit)

**Comment by lyricat** [comment]
不能插入 video 标签吧。

**Comment by alswl** [comment]
久远的回忆，Video 不能在这里插入，需要走微信后台编辑器。

**Comment by lyricat** [comment]
> 久远的回忆，Video 不能在这里插入，需要走微信后台编辑器。

你要不要来维护这个项目

**Comment by alswl** [comment]
前端渣~现在只会写 YAML 了。

我看有些 Alternative 项目（好像一部分还是受你这个项目启发），江山带有才人出，此项目历史使命完成了。

**Comment by lyricat** [comment]
可以，很有精神！
