### ISSUE TITLE
无法添加  h1 

### ISSUE THREAD

**Issue by Ben9706** [lyricat/wechat-format#41]
在 css 中我手动添加了 h1 的样式，但在实际编辑器中，# Text使用的仍然是## Text的样式。

**Comment by Ben9706** [comment]
在 css 中我手动添加了 h1 的样式，但在实际编辑器中，`# Text`使用的仍然是`## Text`的样式。

**Comment by 9468305** [comment]
看上去wechat-format并未允许自定义css，除非你fork一份源码来定制自己的编辑器。

**Comment by lyricat** [comment]
嗯 因为我当时很武断地认为，文章标题就是 h1

如果想调整这个默认行为，可以修改这里 https://github.com/lyricat/wechat-format/blob/master/src/assets/scripts/renderers/wx-renderer.js#L85
