### ISSUE TITLE
[Feature Request] 支持latex 公式

### ISSUE THREAD

**Issue by leoleoasd** [lyricat/wechat-format#43]
如题, 如果能支持 latex 公式就好了

**Comment by wxianfeng** [comment]
支持了没 ?

**Comment by lyricat** [comment]
很麻烦。需要生成图片，然后上传图片，然后在微信公众号里引用这个图片，我选择放弃。建议去多骂骂微信公众号团队。

**Comment by leoleoasd** [comment]
生成图片后src里引用base64的图片是否可行？

Lyric Wai ***@***.***> 于 2021年8月24日周二 上午9:05写道：
