### ISSUE TITLE
请问可以问下哪个文件是关于链接转参考文献的吗

### ISSUE THREAD

**Issue by xuelixunhua** [lyricat/wechat-format#49]
能把链接自动转换为参考文献索引，并且附在文字末尾

请问这个事件是靠哪个文件完成的？

**Comment by lyricat** [comment]
https://github.com/lyricat/wechat-format/blob/90df51601070677f85554ad1b4cf025f14a20181/src/assets/scripts/renderers/wx-renderer.js#L138

这个
