### ISSUE TITLE
非常好用！希望能像http://md.aclickall.com/一样，能提供自定义css那就更好了

### ISSUE THREAD

**Issue by djmaxwow** [lyricat/wechat-format#8]
我们前端团队的公众号一直用http://md.aclickall.com 来排的，确实是遇到了作者说到的ul li被公众号重排的问题，并且参考文献也需要自己手动处理，如果能加上自定义css样式那就更完美拉~

**Comment by cmmei** [comment]
这个可以自定义 CSS 的哦。我是修改 `index.html` 文件。

**Comment by lyricat** [comment]
src/themes/ 下面已经有 theme 了，谁做个选项来支持一下？

**Comment by djmaxwow** [comment]
好的，我可能没看仔细，谢谢

**Comment by pengloo53** [comment]
@djmaxwow 默认的样式挺好看的，只是默认字体大小 16px 小了，新增了一个自定义配置项。#18

**Comment by lyricat** [comment]
前天 @pengloo53 做了主题支持，你可以看看。
